// import ArticlesList from "./ArticlesList"

const ArticleContent = [
    {
        name: 'Notepad App',
        title: 'Notepad Entry',
        content: [
            `Pellentesque fringilla magna quis ex euismod, at porta diam convallis. Integer porta dapibus magna non lacinia. Donec non neque ante. Vivamus rhoncus blandit risus, a placerat ante auctor ut. Vivamus ornare ligula id enim scelerisque sollicitudin vitae id nulla. Quisque iaculis dolor a hendrerit interdum. Proin nec massa id mauris gravida porttitor. In mollis, sapien et tempus sodales, tellus mi commodo augue, nec lobortis nulla enim ac justo. Aliquam eu tincidunt ante, sit amet facilisis diam. Pellentesque rutrum, ex non sagittis dignissim, metus lectus fermentum ante, id convallis arcu orci lacinia turpis. In id lorem sit amet dui fringilla hendrerit. Proin sed risus eros. Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`,
            `Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`
        ]
    },
    {
        name: 'How to Navigate the World Wide Wow',
        title: 'How to Navigate the World Wide Wow',
        content: [
            `Pellentesque fringilla magna quis ex euismod, at porta diam convallis. Integer porta dapibus magna non lacinia. Donec non neque ante. Vivamus rhoncus blandit risus, a placerat ante auctor ut. Vivamus ornare ligula id enim scelerisque sollicitudin vitae id nulla. Quisque iaculis dolor a hendrerit interdum. Proin nec massa id mauris gravida porttitor. In mollis, sapien et tempus sodales, tellus mi commodo augue, nec lobortis nulla enim ac justo. Aliquam eu tincidunt ante, sit amet facilisis diam. Pellentesque rutrum, ex non sagittis dignissim, metus lectus fermentum ante, id convallis arcu orci lacinia turpis. In id lorem sit amet dui fringilla hendrerit. Proin sed risus eros. Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`,
            `Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`,
            `Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`,
            `Pellentesque fringilla magna quis ex euismod, at porta diam convallis. Integer porta dapibus magna non lacinia. Donec non neque ante. Vivamus rhoncus blandit risus, a placerat ante auctor ut. Vivamus ornare ligula id enim scelerisque sollicitudin vitae id nulla. Quisque iaculis dolor a hendrerit interdum. Proin nec massa id mauris gravida porttitor. In mollis, sapien et tempus sodales, tellus mi commodo augue, nec lobortis nulla enim ac justo. Aliquam eu tincidunt ante, sit amet facilisis diam. Pellentesque rutrum, ex non sagittis dignissim, metus lectus fermentum ante, id convallis arcu orci lacinia turpis. In id lorem sit amet dui fringilla hendrerit. Proin sed risus eros. Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`,
            `Pellentesque fringilla magna quis ex euismod, at porta diam convallis. Integer porta dapibus magna non lacinia. Donec non neque ante. Vivamus rhoncus blandit risus, a placerat ante auctor ut. Vivamus ornare ligula id enim scelerisque sollicitudin vitae id nulla. Quisque iaculis dolor a hendrerit interdum. Proin nec massa id mauris gravida porttitor. In mollis, sapien et tempus sodales, tellus mi commodo augue, nec lobortis nulla enim ac justo. Aliquam eu tincidunt ante, sit amet facilisis diam. Pellentesque rutrum, ex non sagittis dignissim, metus lectus fermentum ante, id convallis arcu orci lacinia turpis. In id lorem sit amet dui fringilla hendrerit. Proin sed risus eros. Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`,
            `Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`,
            `Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`,
            `Pellentesque fringilla magna quis ex euismod, at porta diam convallis. Integer porta dapibus magna non lacinia. Donec non neque ante. Vivamus rhoncus blandit risus, a placerat ante auctor ut. Vivamus ornare ligula id enim scelerisque sollicitudin vitae id nulla. Quisque iaculis dolor a hendrerit interdum. Proin nec massa id mauris gravida porttitor. In mollis, sapien et tempus sodales, tellus mi commodo augue, nec lobortis nulla enim ac justo. Aliquam eu tincidunt ante, sit amet facilisis diam. Pellentesque rutrum, ex non sagittis dignissim, metus lectus fermentum ante, id convallis arcu orci lacinia turpis. In id lorem sit amet dui fringilla hendrerit. Proin sed risus eros. Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`
        ]
    },
    {
        name: 'Rainbow Text Entry',
        title: 'Rainbow Text Entry',
        content: [
            `Pellentesque fringilla magna quis ex euismod, at porta diam convallis. Integer porta dapibus magna non lacinia. Donec non neque ante. Vivamus rhoncus blandit risus, a placerat ante auctor ut. Vivamus ornare ligula id enim scelerisque sollicitudin vitae id nulla. Quisque iaculis dolor a hendrerit interdum. Proin nec massa id mauris gravida porttitor. In mollis, sapien et tempus sodales, tellus mi commodo augue, nec lobortis nulla enim ac justo. Aliquam eu tincidunt ante, sit amet facilisis diam. Pellentesque rutrum, ex non sagittis dignissim, metus lectus fermentum ante, id convallis arcu orci lacinia turpis. In id lorem sit amet dui fringilla hendrerit. Proin sed risus eros. Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`,
            `Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`,
            `Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`,
            `Pellentesque fringilla magna quis ex euismod, at porta diam convallis. Integer porta dapibus magna non lacinia. Donec non neque ante. Vivamus rhoncus blandit risus, a placerat ante auctor ut. Vivamus ornare ligula id enim scelerisque sollicitudin vitae id nulla. Quisque iaculis dolor a hendrerit interdum. Proin nec massa id mauris gravida porttitor. In mollis, sapien et tempus sodales, tellus mi commodo augue, nec lobortis nulla enim ac justo. Aliquam eu tincidunt ante, sit amet facilisis diam. Pellentesque rutrum, ex non sagittis dignissim, metus lectus fermentum ante, id convallis arcu orci lacinia turpis. In id lorem sit amet dui fringilla hendrerit. Proin sed risus eros. Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`
        ]
    },
    {
        name: 'The Truth About Geckos',
        title: 'The Truth About Geckos',
        content: [
            `Here is some placeholder content for an article about geckos.`,
            `Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`,
            `Pellentesque fringilla magna quis ex euismod, at porta diam convallis. Integer porta dapibus magna non lacinia. Donec non neque ante. Vivamus rhoncus blandit risus, a placerat ante auctor ut. Vivamus ornare ligula id enim scelerisque sollicitudin vitae id nulla. Quisque iaculis dolor a hendrerit interdum. Proin nec massa id mauris gravida porttitor. In mollis, sapien et tempus sodales, tellus mi commodo augue, nec lobortis nulla enim ac justo. Aliquam eu tincidunt ante, sit amet facilisis diam. Pellentesque rutrum, ex non sagittis dignissim, metus lectus fermentum ante, id convallis arcu orci lacinia turpis. In id lorem sit amet dui fringilla hendrerit. Proin sed risus eros. Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`,
            `Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`,
            `Pellentesque fringilla magna quis ex euismod, at porta diam convallis. Integer porta dapibus magna non lacinia. Donec non neque ante. Vivamus rhoncus blandit risus, a placerat ante auctor ut. Vivamus ornare ligula id enim scelerisque sollicitudin vitae id nulla. Quisque iaculis dolor a hendrerit interdum. Proin nec massa id mauris gravida porttitor. In mollis, sapien et tempus sodales, tellus mi commodo augue, nec lobortis nulla enim ac justo. Aliquam eu tincidunt ante, sit amet facilisis diam. Pellentesque rutrum, ex non sagittis dignissim, metus lectus fermentum ante, id convallis arcu orci lacinia turpis. In id lorem sit amet dui fringilla hendrerit. Proin sed risus eros. Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`,
            `In mollis, sapien et tempus sodales, tellus mi commodo augue, nec lobortis nulla enim ac justo. Aliquam eu tincidunt ante, sit amet facilisis diam. Pellentesque rutrum, ex non sagittis dignissim, metus lectus fermentum ante, id convallis arcu orci lacinia turpis. In id lorem sit amet dui fringilla hendrerit. Proin sed risus eros. Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`
        ]
    },
    {
        name: 'Hello World!',
        title: 'Hello World!',
        content: [
            `Hello World!`,
            `Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`,
            `Pellentesque fringilla magna quis ex euismod, at porta diam convallis. Integer porta dapibus magna non lacinia. Donec non neque ante. Vivamus rhoncus blandit risus, a placerat ante auctor ut. Vivamus ornare ligula id enim scelerisque sollicitudin vitae id nulla. Quisque iaculis dolor a hendrerit interdum. Proin nec massa id mauris gravida porttitor. In mollis, sapien et tempus sodales, tellus mi commodo augue, nec lobortis nulla enim ac justo. Aliquam eu tincidunt ante, sit amet facilisis diam. Pellentesque rutrum, ex non sagittis dignissim, metus lectus fermentum ante, id convallis arcu orci lacinia turpis. In id lorem sit amet dui fringilla hendrerit. Proin sed risus eros. Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`,
            `In mollis, sapien et tempus sodales, tellus mi commodo augue, nec lobortis nulla enim ac justo. Aliquam eu tincidunt ante, sit amet facilisis diam. Pellentesque rutrum, ex non sagittis dignissim, metus lectus fermentum ante, id convallis arcu orci lacinia turpis. In id lorem sit amet dui fringilla hendrerit. Proin sed risus eros. Ut gravida tortor nec eros imperdiet, vitae vehicula magna dignissim. Donec tempor nisl eu nibh interdum, id maximus risus pulvinar. Etiam vitae volutpat libero, ac fermentum lectus`
        ]
    },
];

export default ArticleContent;